# Generated by Django 4.2.7 on 2023-11-15 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportTypes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="UIManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("text_description", models.TextField(max_length=200)),
                ("UI_position", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DataManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("report_number", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "report_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.reporttypes",
                    ),
                ),
            ],
        ),
    ]
