# Generated by Django 4.2.7 on 2023-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamanager",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
